name: build

on:
  push:
    branches:
    - master
    - 'feature/**'
    
  pull_request:
    branches:
    - master
    - 'feature/**'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up GraalVM
      uses: DeLaGuardo/setup-graalvm@master
      with:
        graalvm-version: '22.2.0.java11'
    - name: install native-image
      run: gu install native-image
    - name: Grant execute permission for mvnw
      run: chmod +x mvnw
    - name: Build with maven
      run: ./mvnw package -Pnative
